### ISSUE TITLE
Multiple circles

### ISSUE THREAD

**Issue by n8fr8** [guardianproject/OpenCircle#2]
Could the App have a personal Circle and Emergency Circle too, and be able to send a Emergency message to both at the same time?

**Comment by n8fr8** [comment]
"create different circles for different situations"

**Comment by Mikaela** [comment]
Would this issue include circles per country? If I need to trigger the app in home country, it's not that useful to alert my partner more than thousand kilometres away and if I am there, it would be better to alert local friends instead of people at home.

**Comment by n8fr8** [comment]
We are definitely considering that. The underlying new codebase system is built on Matrix (matrix.org), which essentially an encrypted group messaging platform. This means you can support groups/room easily with different members. We just need to figure out how to represent this in the user interface, without turning the app into Yet Another Messaging App. 

Thanks so much for the feedback!

**Comment by n8fr8** [comment]
Multiple circles are now supported, in the beta, and in the full app we are launching in November
