### ISSUE TITLE
Home

### ISSUE THREAD

**Issue by cstiens** [guardianproject/OpenCircle#26]
Here's an overview of the design for this view: https://youtu.be/TSKyD35qojc
From this view, you can—

* Set your status — Tap on 'What's your status' input bar to open the *Add my status* view
* Update your emoji state
* Swipe through the statuses of each member
* Swipe up to make a make a status full screen
* Tap on a member's avatar to jump to their status view within the home screen
* Tap on your avatar to open your status
* Swipe to *Hotlines* and *Resources* views

**View states**
- [ ] With empty status
- [ ] With status

**Status states (ring around avatar)**
* Purple gradient = new status & unread
* Gray = status set & read
* Nothing = no status set
* Red = new status & unread & marked as urgent

![sup_home01-no-status](https://user-images.githubusercontent.com/1434597/47752096-908e8d80-dc61-11e8-9fcf-00894f8522e3.png)

![sup_home02](https://user-images.githubusercontent.com/1434597/47752109-94221480-dc61-11e8-9724-41f55ac3ad00.png)

![sup-home03-emoji](https://user-images.githubusercontent.com/1434597/47752166-b9168780-dc61-11e8-9d42-c468ecea94ce.png)

**Comment by n8fr8** [comment]
oops didn't meant to check that box!

**Comment by cstiens** [comment]
@N-Pex I just added a lot of good info here.

**Comment by N-Pex** [comment]
@cstiens Great, thanks, in progress! =)

**Comment by N-Pex** [comment]
@cstiens Quick question on this "Tap on a member's avatar to jump to their status view within the home screen":

Makes sense. But how do you assign/unassign/change a contact in your circle. I guess that's on another screen?

**Comment by cstiens** [comment]
@N-Pex Here are the specs for this view. 

> Makes sense. But how do you assign/unassign/change a contact in your circle. I guess that's on another screen?

Yeah. Not sure yet. We'll work that out. :)

![sup_home01-no-status-fontspecs](https://user-images.githubusercontent.com/1434597/47820060-589f4d00-dd2a-11e8-866f-caceaf743f02.png)


![sup_home01-no-status-measurements](https://user-images.githubusercontent.com/1434597/47820051-50dfa880-dd2a-11e8-921c-b84bc3e785fb.png)
