### ISSUE TITLE
Add content to Mexico City demo

### ISSUE THREAD

**Issue by cstiens** [guardianproject/OpenCircle#32]
@N-Pex I've attached a text file of the translated strings and avatars for the demo content, along with an svg of the whatsapp icon. Thank you!

[av_squares.zip](https://github.com/guardianproject/OpenCircle/files/2560196/av_squares.zip)

[statuses-translated.txt](https://github.com/guardianproject/OpenCircle/files/2560197/statuses-translated.txt)

[iconmonstr-whatsapp-1.svg.zip](https://github.com/guardianproject/OpenCircle/files/2560203/iconmonstr-whatsapp-1.svg.zip)

**Comment by N-Pex** [comment]
Thanks @cstiens ! Do we have translations for these:

Safe
Unsure
Scared
Calling
Messaging
WhatsApp
Remove
Update
Status removed

**Comment by cstiens** [comment]
**Safe**
Segura 

**Unsure**
Insegura 

**Scared**
Asustada 

**Calling**
Llamando

**Messaging**
Mensajeando

**WhatsApp**
WhatsApp

Still need:

- [ ] Remove
- [ ] Update
- [ ] Status removed
- [ ] Pre-populated messages

**Comment by kckthx** [comment]
**Remove**
Remover

**Update**
Actualizar

**Status Removed**
Estatus removido

PRE-POPULATED MESSAGES
_The statements (grey)_ 

**Everything is okay.**
Todo va bien.

**I'm being threatened.**
Estoy siendo amenazada (o).

**Frightened for my safety.**
Temiendo por mi seguridad.

**I'm being trolled.**
Me estan troleando.

**Fleeing.**
Huyendo.


_The actions (purple)_
**Help me**
Ayudenme

**Call me**
Llamame

**What should I do**
¿Que debo hacer?

**Meet me**
Reúnete conmigo

**Comment by cstiens** [comment]
@N-Pex we've added the missing translations here.
