### ISSUE TITLE
Emoji Keyboard Crash

### ISSUE THREAD

**Issue by kckthx** [guardianproject/OpenCircle#39]
Response emoji keyboard crashes sometimes but not every time.

**Comment by N-Pex** [comment]
I can't repro the crash. But I noticed at least on my device the emoji keyboard shows one "flavor" of emojis, while the view in our app show another. Font issue? Maybe should investigating if there are other emoji keyboards out there.

**Comment by kckthx** [comment]
@N-Pex @n8fr8 @cstiens this also may be that there are different emojis across google/windows?
