### ISSUE TITLE
Time Stamp Confusion?

### ISSUE THREAD

**Issue by kckthx** [guardianproject/OpenCircle#40]
#When I respond to statuses with an emoji, the most recently posted one is saying “no update” or “sin actualizad” as the time it was posted at/time stamp. -- 
when I tap back or out of it and then back in, it will say “just now” or “justo ahora” #

(tested 3 times, this happened 2 times)

**Comment by n8fr8** [comment]
This might just be because we are using mocked up data

**Comment by kckthx** [comment]
![screenshot_20181120-233936_co6-dev](https://user-images.githubusercontent.com/36669955/48784466-5a648c80-eca8-11e8-8d37-1ea56e4b0c67.jpg)
![screenshot_20181120-233948_co6-dev](https://user-images.githubusercontent.com/36669955/48784472-5cc6e680-eca8-11e8-8892-e2ab88beef86.jpg)
