### ISSUE TITLE
Delete Emoji Responses

### ISSUE THREAD

**Issue by kckthx** [guardianproject/OpenCircle#41]
When I tap the "add emoji" icon and respond with a passive emoji, mine will show up as blue, and I can tap it again to delete it.

![sup-response-delete](https://user-images.githubusercontent.com/36669955/48781704-2dad7680-eca2-11e8-98f1-c32cb3bd6def.png)

Likewise, if I tap an emoji response that someone else has left, I can add to it instead of having to tap the "add emoji" icon again

![sup-response-add](https://user-images.githubusercontent.com/36669955/48782123-1753ea80-eca3-11e8-9b29-d0032359e123.png)

**Comment by N-Pex** [comment]
I have a few questions on this, regarding the list to the left of the "smiley with plus":

Is this a list of all reply emojis from people, i.e. it is actually the same as the tabs in the reply view pager below (minus the "call" and the "message" icons)? Or is this just a list of the replies YOU have sent? Should you be able to add/remove more than one emoji?

**Comment by kckthx** [comment]
@N-Pex yes, it is a list of ALL reply emojis minus call and message.
Any that I have sent will be blue though -
So if someone else had already responded with the prayer hands, I could tap the button/icon and it would add the same emoji for me (so it would turn blue with a 2 next to it) -- OR I could add it straight from the emoji keyboard. 

You can add as many as you want, but can only remove ones that you have set. Does that make sense?

**Comment by N-Pex** [comment]
@kckthx Yes, got it, thanks!

**Comment by N-Pex** [comment]
@kckthx Ok, added this in the latest (3008) build. There's one problematic area here (and hence a little buddy at the moment): I am wondering about the height of things, what is fixed and what is not. The thing causing problems is the tabs with lists of replies at the bottom. While for example "call" or one of the emojis can have 1 entry, some can have several, and thus need more space.

Say that the 3rd tab has 3 entries, while the 1st has only one. Should the first tab then have lots of blank space below the entry, to allow for the 3 entries on tab 3?

**Comment by kckthx** [comment]
@N-Pex Ah I see! 
Let's add the blank space to fit the tab with the most responses.
