### ISSUE TITLE
Add Friends

### ISSUE THREAD

**Issue by cstiens** [guardianproject/OpenCircle#51]
We're working on the workflow for adding people to your circle. I've attached the view that shows options. @n8fr8 This is what I wanted to discuss with you.

Here are our current thoughts:
1. In using the app, you most likely will want to have the phone number of the people in your app linked, so you can easily call or text them from their status screen. This is why we've shown the phone number first.

2. People get wearing about permissions, especially when an app wants access to your contacts. So, we've made that secondary.

3. We've talked about QR codes as an option for adding people, so we've represented it here. If you add someone this way, you wouldn't have their phone number. But you could still launch WhatsApp from a friends status view, and interact with emojis. :)

![add](https://user-images.githubusercontent.com/1434597/49952336-5f8cb400-fec1-11e8-92c5-4337a2b8aee3.png)

**Comment by n8fr8** [comment]
contact adding done via username, invite link, qr code, etc
