### ISSUE TITLE
public beta launch landing page

### ISSUE THREAD

**Issue by n8fr8** [guardianproject/OpenCircle#52]

**Comment by cstiens** [comment]
Here's the poster created for the Colombia workshop—

[Poster-Layouts-Spanish.pdf](https://github.com/guardianproject/OpenCircle/files/2765081/Poster-Layouts-Spanish.pdf)

We'll add the images and text to this issue shortly.

**Comment by kckthx** [comment]
@n8fr8 here is the image of the screens and the copy in english and spanish for the splash page

![beta-image](https://user-images.githubusercontent.com/36669955/51271541-707f8800-198d-11e9-94e0-95d903d241cb.png)
https://docs.google.com/document/d/1NX73PvbF3eiEaLyVg0WKirve616LN1Z_3S5lwspT6Tw/edit?usp=sharing

**Comment by cstiens** [comment]
Here's an interim logo for the beta release. @n8fr8 I did 2 different colors. If we want it more distinct from the original Circle of 6, I would go with the yellow.

<img width="397" alt="screen shot 2019-01-21 at 9 10 35 am" src="https://user-images.githubusercontent.com/1434597/51482718-d046ac00-1d5c-11e9-875e-53b80811313a.png">

[beta-cirlce.zip](https://github.com/guardianproject/OpenCircle/files/2779434/beta-cirlce.zip)

**Comment by n8fr8** [comment]
Thank you!
